// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface DismissSegue: UIStoryboardSegue
-(IBAction) perform;

@end

@interface UIColor: NSObject
@end

@interface DiscourseScreen: UIViewController
-(IBAction) viewDidLoad;

@end

@interface HomeScreenForumCell: UITableViewCell
@end

@interface HomeScreen: UIViewController

@property IBOutlet UITableView * table;
@property IBOutlet UISearchBar * search_bar;
@property IBOutlet HomeScreenForumCell * forum_cell;

-(IBAction) viewDidLoad;

@end

@interface SettingsScreen: UIViewController
@end

