// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreFoundation/CoreFoundation.h>
#import <CFNetwork/CFNetwork.h>
#import <CoreAudio/CoreAudio.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <CoreLocation/CoreLocation.h>
#import <AddressBookUI/AddressBookUI.h>
#import <CoreData/CoreData.h>
#import <WebKit/WebKit.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <Security/Security.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface DismissSegue: UIStoryboardSegue
-(IBAction) perform;

@end

@interface UIColor: NSObject
@end

@interface Site: NSObject
-(IBAction) unread_total;
-(IBAction) encodeWithCoder:(id) encoder;
-(IBAction) initWithCoder:(id) decoder;
-(IBAction) save;

@end

@interface DiscourseScreen: UIViewController
-(IBAction) viewDidLoad;
-(IBAction) web_view;
-(IBAction) build_web_view;

@end

@interface HomeScreenForumCell: UITableViewCell
@end

@interface HomeScreenViewModel: NSObject
-(IBAction) initialize;
-(IBAction) sites;

@end

@interface HomeScreen: UIViewController

@property IBOutlet UITableView * table;
@property IBOutlet UISearchBar * search_bar;
@property IBOutlet HomeScreenForumCell * forum_cell;

-(IBAction) viewDidLoad;
-(IBAction) view_model;
-(IBAction) searchBarTextDidBeginEditing:(id) search_bar;
-(IBAction) searchBarCancelButtonClicked:(id) search_bar;
-(IBAction) numberOfSectionsInTableView:(id) tableView;

@end

@interface SettingsScreen: UIViewController
@end

