// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation DismissSegue
@end

@implementation UIColor
@end

@implementation Site
@end

@implementation DiscourseScreen
@end

@implementation HomeScreenForumCell
@end

@implementation HomeScreenViewModel
@end

@implementation HomeScreen
@end

@implementation SettingsScreen
@end

