// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation DismissSegue
@end

@implementation UIColor
@end

@implementation DiscourseScreen
@end

@implementation HomeScreenForumCell
@end

@implementation HomeScreen
@end

@implementation SettingsScreen
@end

